# Create the ecmean development environment:
# mamba env create -f dev-environment.yml 
# or 
# conda env create -f dev-environment.yml

name : dev-ecmean
channels:
  - conda-forge
dependencies:
  - python>=3.9,<=3.14
  - libnetcdf
  - xesmf
  - eccodes
  - cdo
  - ncview
  - ipykernel
  - pip
  - pip:
    - -e .[all]

